### ISSUE TITLE
Hello, I cannot build yer-face using CMAKE

### ISSUE THREAD

**Issue by rnjena** [markleybros/yer-face#18]
Hello, I cannot build yer-face using CMAKE

CMAKE cannot find dlib.

I installed dlib, but it cannot find the dlib.

Could you check the error?

I used CMAKE 3.14.0 and dlib 19.4 and 19.17

Thanks

**Comment by alexmarkley** [comment]
Hi @rnjena, thanks for checking out the project! I am happy to help you get YerFace compiled on your machine.

To make progress understanding the problem, can you give me more information about your situation? What operating system & version are you using? What method did you use to install dlib? What is the output on the console when you run cmake?

I’m in meetings today and also going to be traveling by air for several hours, so my availability will be a little constrained, but if you get back to me quickly with this information I will respond as soon as I can.

Thanks!

**Comment by rnjena** [comment]
Hello!

My operating system is ,
Windows 10

I installed dlib (http://dlib.net/) with cmake 3.14.0
I used both dlib version  19.4 and 19.17.

I used a cmake GUI version in all install process including dlib and yerface.

Cmake shows

'Error in configuration process, project files may be invalid.'

with popup windows.
and

Log shows,

-----------------------------------------------------------------------------------------------

CMake Error at CMakeLists.txt:61 (find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.

-----------------------------------------------------------------------------------------------


Thanks!

Best,

**Comment by alexmarkley** [comment]
Wow that’s exciting. I have not yet tried building my project on Windows, so you are blazing a trail here.

I definitely intend to produce Windows binary releases once we are just a little bit more stable, but we haven’t gotten there quite yet.

Can you tell me what compiler or dev toolkit you are using? Do you know what the full disk path is where dlib got installed? Can you provide a screenshot or file listing with details of the dlib installation?

Please be aware also, that dlib is only one of our build dependencies. You will see a more complete list of dependencies if you look in the documentation for either Fedora or Ubuntu, where I detail the setup process for either of those Linux-based operating systems.

If you want to create a working build environment, you will need at least Dlib, OpenCV, SDL2, ffmpeg (libav*), and pocketsphinx. 

Final question: Do you have a particular desire to be able to compile YerFace yourself? (For example, are you planning on contributing to development?) Or would a Windows-compatible binary distribution be enough?

Thanks,
—Alex

**Comment by alexmarkley** [comment]
I haven't heard back in a few days, so unless I hear back from you @rnjena I will go ahead with the following:

- I will work on producing Windows binary builds of YerFace, so as to enable early adopters like yourself to experiment with the program.
- I will try to produce documentation on building for Windows. (Either natively or in a cross-compile environment, whichever turns out to be easier.)
- This issue will be subsequently closed as resolved.

I won't have time to work on this until my current optimization branch stabilizes and makes it into master. After that I will work on this.

Thanks,
--Alex

**Comment by alexmarkley** [comment]
I wanted to provide an update on this issue, since it's been a few weeks.

I have successfully introduced automated builds for Linux ([see yerface.live to download](https://yerface.live/download/)). However, Windows builds are turning out to be a little more elusive.

Initially, my plan was to use MinGW as a cross compile environment to produce Windows binaries from a traditional Linux containerized build.

However, this turned out to be impossible because CUDA cannot be cross-compiled.

I am now investigating whether or not I can automate a build process using Windows as the host OS within AWS EC2 and/or AWS CodeBuild. The outcome of this issue depends on the complexity of that.

(Note, I am not interested in manual processes or one-off builds. For multiple reasons, I would rather not produce anything for Windows if it cannot be automated.)

**Comment by alexmarkley** [comment]
Hi @rnjena I am pleased to report that initial (highly experimental) Windows support has been introduced. Please see [our download page](https://yerface.live/download/) for the latest build.

I hope this satisfies the spirit of this issue, and I look forward to further feedback if you have a chance to test the build.

Thanks,
--Alex
