### ISSUE TITLE
Does not run on Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by probonopd** [markleybros/yer-face#24]
Which system was this built on? It does not run on Ubuntu 16.04 (xenial): `usr/bin/yer-face: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-8340/usr/bin/yer-face)`

References:
* https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems
* https://github.com/AppImage/appimage.github.io/pull/1454

**Comment by alexmarkley** [comment]
Thanks for reaching out on this! I'm still experimenting with the building and packaging process to give this binary the best chance of working for people. I do use checkrt to try and load the correct runtime environment, but I guess it's not including glibc.

Aside from a modern version of glibc, this app is going to require a reasonably recent version of the NVidia proprietary drivers, specifically something compatible with CUDA 10.1.

Currently my CI Dockerfile is `FROM ubuntu:18.04` although I have no reason to believe that `FROM ubuntu:16.04` would not work with some tweaking. I don't want to target 14.04 because it's effectively EOL at this point.

Thanks again for checking in on this, and please let me know if you have any suggestions or improvements to offer.

**Comment by probonopd** [comment]
Yes, `FROM ubuntu:16.04` would be good. It would most likely solve this issue.

**Comment by alexmarkley** [comment]
Thanks for reaching out on this! I'm still experimenting with the building and packaging process to give this binary the best chance of working for people. I do use checkrt to try and load the correct runtime environment, but I guess it's not including glibc.

Aside from a modern version of glibc, this app is going to require a reasonably recent version of the NVidia proprietary drivers, specifically something compatible with CUDA 10.1.

Currently my CI Dockerfile is `FROM ubuntu:18.04` although I have no reason to believe that `FROM ubuntu:16.04` would not work with some tweaking. I don't want to target 14.04 because it's effectively EOL at this point.

Thanks again for checking in on this, and please let me know if you have any suggestions or improvements to offer.

**Comment by alexmarkley** [comment]
@probonopd I did a little poking around here and I think I have it working on Ubuntu 16.04.

I needed to compile a few more dependencies from source, because the Ubuntu repositories for 16.04 are too old. (FFmpeg specifically) However, I think the extra effort was worth it if it produces binaries that are compatible with a wider range of systems.

**Comment by alexmarkley** [comment]
@probonopd Please give the latest build `yer-face-0.0.1-master-20190414-5f01159` a try. It's available at https://yerface.live/download/

**Comment by alexmarkley** [comment]
Since I haven't heard back, I'm going to assume that this issue is resolved. Please reopen or create a new issue if appropriate.

Thanks,
--Alex

**Comment by probonopd** [comment]
Is `/dev/video0` required for the application to even launch?

Getting

```
Dropping all Linux capabilities and enforcing default seccomp filter
firejail ./BeingTested.AppImage VERBOSE: Utilities: Checking if "/run/firejail/appimage/.appimage-8309/usr/local/share/yer-face/yer-face-config.json" exists.
VERBOSE: YerFace: Opening and parsing config file: "/run/firejail/appimage/.appimage-8309/usr/local/share/yer-face/yer-face-config.json"
DEBUG: Status: Status object constructed and ready to go!
INFO: Status: Running is set to TRUE...
INFO: Status: Processing is set to RESUMED...
DEBUG: Metrics<YerFace>: Metrics object constructed and ready to go!
DEBUG: Metrics<FrameServer>: Metrics object constructed and ready to go!
DEBUG: WorkerPool<FrameServer.Herder>: NumWorkers explicitly set to 1.
VERBOSE: WorkerPool<FrameServer.Herder>: Worker Thread #1 Alive!
DEBUG: WorkerPool<FrameServer.Herder>: WorkerPool object constructed with NumWorkers: 1
DEBUG: FrameServer: FrameServer constructed and ready to go!
DEBUG: Metrics<PreviewHUD>: Metrics object constructed and ready to go!
DEBUG: Status: Preview Debug Density set to 1
DEBUG: WorkerPool<PreviewHUD>: Calculating NumWorkers: System has 2 CPUs, at 0.50 Workers per CPU that's 1 NumWorkers.
DEBUG: WorkerPool<PreviewHUD>: WorkerPool object constructed with NumWorkers: 1
DEBUG: PreviewHUD: PreviewHUD object constructed and ready to go.
VERBOSE: WorkerPool<PreviewHUD>: Worker Thread #1 Alive!
DEBUG: FFmpegDriver: FFmpegDriver object constructed and ready to go! Low Latency mode is DISABLED.
INFO: FFmpegDriver: Opening media /dev/video0...
[video4linux2,v4l2 @ 0x3bdf3c0] Cannot open video device /dev/video0: No such file or directory
ERROR: FFmpegDriver: input file could not be opened AVERROR: (-2) No such file or directory
Uncaught exception: input file could not be opened
```

**Comment by alexmarkley** [comment]
@probonopd thanks for getting back to me on this. I'm pleased to see that the dynamic linker is able to kick off the process now -- that's progress!

The direct answer to your question is no, /dev/video0 is not required to start the program. However, since `yer-face` is currently primarily a CLI, it does require **some** input video in order to successfully process it.

I do admit that the default (no arguments) behavior is probably not that useful. I'm open to suggestion.

If you want detailed usage, try `--help` or if you just want to test for a zero exit code, do `--version`.

I do have plans to (eventually) create a GUI launcher mode for the default behavior, but that might be a ways down the road. (Unless some generous programmer donates some free time!)

Can you give me some indication of what you're trying to do? That would maybe help me understand so we can resolve this more efficiently.

**Comment by probonopd** [comment]
Can you make it so that if invoked without any command line arguments it does something useful , e.g., show a dialog box, and exit without an error code? (That's currently required to pass the automated test for appimage.github.io). Thanks!

**Comment by alexmarkley** [comment]
There won't be a dialog box until or unless I make the appropriate design decisions about building a GUI for the tool.

However, I can treat "no arguments" as a special case. Normally if a usage message is displayed I consider that a non-success condition because:

1. No useful work was performed.
2. Either the user explicitly or implicitly indicated that they do not know how to use the tool, which means no work **can** be successfully completed (by definition).

As I said though, I think I can consider "no arguments" as a special case. Give me a few minutes and I'll take a whack at this.

**Comment by alexmarkley** [comment]
@probonopd please give the latest build `yer-face-0.0.1-master-20190419-a9d0c59` a try. It should do what you're asking for. Thanks!

**Comment by probonopd** [comment]
Thank you. It would be great if those were available at https://github.com/markleybros/yer-face/releases - any chance?

**Comment by probonopd** [comment]
```
./BeingTested.AppImag
YerFace! A stupid facial performance capture engine for cartoon animation. (yer-face-0.0.1-master-20190419-a9d0c59)
Usage: yer-face [params] 

	-C, --configFile
```

Looks like this is a command line application. In that case, it needs `Terminal=true` to be set in the desktop file.

**Comment by alexmarkley** [comment]
@probonopd The application isn’t stable enough yet to warrant a stable or supported release, so that’s why there are no releases tagged or published on the Github repository.

With regards to the desktop file, you can see in the automated build process that we are currently using an auto-generated desktop file. I would happily consider a pull request that introduces an improved desktop file.

Thanks again for engaging on this!
—Alex

**Comment by probonopd** [comment]
Hi Alex, I don't know how you auto-generate the desktop file, but adding a simple line `Terminal=true` should do the trick.
